name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build
      working-directory: ./frontend
      run: npm run build

    - name: Deploy
      working-directory: ./frontend
      run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK }}

