name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build swagger
        shell: bash
        run: |
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.9.4.zip
          unzip v5.9.4.zip
          cp -r swagger-ui-5.9.4/dist/. backend/_build
          cd backend/_build
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|swagger-output.json|' swagger-initializer.js
          ls
          ls ../..
          pwd

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: backend/_build
