name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build swagger
        shell: bash
        run: |
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.9.4.zip
          unzip v5.9.4.zip
          ls
          pwd
          cp backend/_build/swagger-output.json swagger-ui-5.9.4/dist          


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./swagger-ui-5.9.4/dist
